### ISSUE TITLE
LOG IN PROBLEM

### ISSUE THREAD

**Issue by Mathews03** [Smash-Soda-Team/smash-soda#11]
I press the login button but does nothing. It probably must send me to a website for a login and put a code. Create account button works properly.

**Comment by MickeyUK** [comment]
Unfortunately Parsec have disabled authentication for third party apps, essentially killing Parsec Soda! :(

At first it seemed that Parsec were having discussions on how to support Soda going forward, but now it seems this is not going to happen.

I am working on an alternative to Parsec Arcade which I shall post more about on my website soon: https://parelax.net
