### ISSUE TITLE
Gamepad Kill Switch

### ISSUE THREAD

**Issue by Remixful** [Smash-Soda-Team/smash-soda#4]
It'd be awesome if we could have two (preferably configurable) hotkeys to quit SmashSoda and another to lock all controllers. I get a lot of trigger happy players sometimes and this would be an easy solution instead of fiddling around trying to click on the lock all controllers button in time.

**Comment by MickeyUK** [comment]
I'll see what I can do!

**Comment by MickeyUK** [comment]
I added a new CTRL + L hotkey for locking/unlocking everybody's pads, as well as CTRL + B for pressing everybody's B twice. I'll add a hotkey for closing application for sometime...but for now can use Alt + F4. :D

https://github.com/Smash-Soda-Team/smash-soda/releases/tag/2.58
