### ISSUE TITLE
Latency Limiter is not always working

### ISSUE THREAD

**Issue by hosikha** [Smash-Soda-Team/smash-soda#5]
Hi, I'm using Smash Soda and set latency limiter to 140, and sometimes guests with ping 200ms or more can join my lobby.

So I think latency limiter is not working at all or maybe sometimes it works, sometimes it doesn't work

**Comment by MickeyUK** [comment]
Yeah a few people have told me it's inconsistent...I shall take a look

**Comment by MickeyUK** [comment]
Fixed in v2.56!
https://github.com/Smash-Soda-Team/smash-soda/releases/tag/2.56
