### ISSUE TITLE
Latency limiter is still not fixed

### ISSUE THREAD

**Issue by hosikha** [Smash-Soda-Team/smash-soda#7]
![Untitled](https://user-images.githubusercontent.com/69895703/210058426-7eecb679-6dbc-4c94-a2f1-7210a0d6f8d3.png)

idk why but it still doesn't working perfectly, but I can confirm it is working, but not perfect.
I have a guess, maybe they are using parsec in their phone to connect to my lobby, or maybe other bug of 'latency limiter'

**Comment by Bruniiin** [comment]
There's definitely an issue with parsec mobile, when I join my own lobby with latency limiter on I can get kicked randomly even though the ms is like 10

**Comment by MickeyUK** [comment]
@hosikha @Bruniiin 

Could you guys download try this pre-release version and tell me if you're still having issues?

https://github.com/Smash-Soda-Team/smash-soda/releases/tag/2.57

**Comment by hosikha** [comment]
![latency problem 2](https://user-images.githubusercontent.com/69895703/210159749-62652cee-514d-4f04-b424-a2f3dd06a017.png)

I can, and I can confirm that 'latency limiter' in this version work worse than the one in 2.56 version, because people with ping higher than 'latency limiter's value' can join more often than 2.56

**Comment by hosikha** [comment]
![lag 3 on](https://user-images.githubusercontent.com/69895703/210193285-0d74f68f-bf71-4735-976d-0ebb99ed3470.png)
![lag 4 off](https://user-images.githubusercontent.com/69895703/210193291-ee105fe3-9d10-4b3b-8ef7-1e81243bb9dd.png)

idk which is opening because the decription of the button tell me it is on when it is 'x' button, and off when it is 'v' button, and I check 2 cases, and the same result

**Comment by hosikha** [comment]
and the 'latency limiter' has a problem too, it only works for some first guests, then later after few guests have joned, it is like not working anymore
